// src/lib/components/Footer.svelte
<script>
	const currentYear = new Date().getFullYear();
	
	const footerLinks = {
		Solutions: ['PoS Systems', 'Sales Automation', 'AI Logistics', 'Analytics'],
		Company: ['About', 'Careers', 'Press', 'Partners'],
		Resources: ['Documentation', 'Help Center', 'Community', 'Blog'],
		Legal: ['Privacy Policy', 'Terms of Service', 'Security', 'Compliance']
	};
</script>

<footer class="py-16 px-4 sm:px-6 lg:px-8 border-t border-white/10 relative overflow-hidden">
	<div class="max-w-7xl mx-auto relative z-10">
		<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8 mb-12">
			<!-- Brand -->
			<div class="lg:col-span-2">
				<div class="text-2xl font-bold bg-gradient-to-r from-blue-400 to-emerald-400 bg-clip-text text-transparent mb-4">
					Workish
				</div>
				<p class="text-slate-400 mb-6 max-w-md leading-relaxed">
					Intelligent Business Solutions for the modern enterprise. Transform your operations with AI-powered technology.
				</p>
				<p class="text-slate-500 text-sm">
					Transform your business today. Contact our specialists.
				</p>
			</div>

			<!-- Links -->
			{#each Object.entries(footerLinks) as [category, links]}
				<div>
					<h4 class="text-white font-semibold mb-4">{category}</h4>
					<ul class="space-y-2">
						{#each links as link}
							<li>
								<a href="#{link.toLowerCase().replace(' ', '-')}" class="text-slate-400 hover:text-white transition-colors duration-300 text-sm">
									{link}
								</a>
							</li>
						{/each}
					</ul>
				</div>
			{/each}
		</div>

		<!-- Bottom -->
		<div class="pt-8 border-t border-white/10 flex flex-col md:flex-row justify-between items-center">
			<p class="text-slate-500 text-sm mb-4 md:mb-0">
				© {currentYear} Workish. All rights reserved.
			</p>
			<div class="flex space-x-6">
				<a href="#privacy" class="text-slate-500 hover:text-white transition-colors duration-300 text-sm">Privacy</a>
				<a href="#terms" class="text-slate-500 hover:text-white transition-colors duration-300 text-sm">Terms</a>
				<a href="#contact" class="text-slate-500 hover:text-white transition-colors duration-300 text-sm">Contact</a>
			</div>
		</div>
	</div>
</footer>

// components/footer.tsx
export default function Footer() {
  return (
    <footer className="py-16 px-6 border-t border-white/10 bg-black/20 backdrop-blur-sm">
      <div className="max-w-7xl mx-auto">
        <div className="grid md:grid-cols-5 gap-12 mb-12">
          <div className="md:col-span-2">
            <h3 className="text-3xl font-bold mb-4">Workish</h3>
            <p className="text-slate-400 text-lg mb-6">Intelligent Business Solutions</p>
            <p className="text-slate-400 leading-relaxed">
              Transform your business today. Contact our specialists to discover how Workish can revolutionize your
              operations.
            </p>
          </div>
          <div>
            <h4 className="font-semibold mb-6 text-lg">Solutions</h4>
            <ul className="space-y-3 text-slate-400">
              <li className="hover:text-white transition-colors cursor-pointer">PoS Systems</li>
              <li className="hover:text-white transition-colors cursor-pointer">Sales Automation</li>
              <li className="hover:text-white transition-colors cursor-pointer">AI Logistics</li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold mb-6 text-lg">Resources</h4>
            <ul className="space-y-3 text-slate-400">
              <li className="hover:text-white transition-colors cursor-pointer">Pricing</li>
              <li className="hover:text-white transition-colors cursor-pointer">Documentation</li>
              <li className="hover:text-white transition-colors cursor-pointer">Case Studies</li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold mb-6 text-lg">Support</h4>
            <ul className="space-y-3 text-slate-400">
              <li className="hover:text-white transition-colors cursor-pointer">Help Center</li>
              <li className="hover:text-white transition-colors cursor-pointer">Contact</li>
              <li className="hover:text-white transition-colors cursor-pointer">About</li>
            </ul>
          </div>
        </div>
        <div className="border-t border-white/10 pt-8 text-center text-slate-400">
          <p>&copy; 2025 Workish. All rights reserved. Intelligent Business Solutions.</p>
        </div>
      </div>
    </footer>
  )
}
